Fix hashlib.md5 call for FIPS-enabled builds
FIPS errors with the following message:

```
  File "/usr/lib/python3.11/site-packages/pdm/cli/commands/run.py", line 167, in _get_script_env
    venv_name = hashlib.md5(os.path.realpath(script_file).encode("utf-8")).hexdigest()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported
```
Since the hash isn't use for cryptographic use we indicate that md5 can be safely used